---
title: "R Notebook"
output: html_notebook
---

```{r}
library(insol)
library(maptools)
library(maps)
library(raster)
library(colorRamps)
library(rgdal)
library(sp)
```


```{r}
temperaturedata <- read.csv("tempdata.csv", as.is = TRUE)
```

```{r}
degreedays <- (temperaturedata[,9] - 18.333)
degreedays[which(degreedays < 0)] = NA
temp_and_dd <- cbind(temperaturedata,degreedays)
```


```{r}
origins <- readShapePoly('TM_WORLD_BORDERS_SIMPL-0/TM_WORLD_BORDERS_SIMPL-0.3.shp')
str(origins)
origins@data
proj4string(origins) <- CRS("+proj=longlat +datum=WGS84")
```

```{r}
plot(origins)
```


```{r}

temp_and_dd <- data.frame(temp_and_dd)
class(temp_and_dd[,4]) <- "numeric"
class(temp_and_dd[,5]) <- "numeric"
nonas <- temp_and_dd[which(is.na(temp_and_dd[,4])==FALSE | is.na(temp_and_dd[,5])==FALSE),]
nonas <- nonas[which(is.na(nonas[,4])==FALSE & is.na(nonas[,5])==FALSE),]

coord <- coordinates((nonas[,5:4]))
pts <- SpatialPointsDataFrame(data =nonas, coords = coord, proj4string = CRS("+proj=longlat +datum=WGS84"))

```


```{r}
#png(file="example%02d.png", width=200, height=200)
for (i in 1:30){
plot(origins)
plot(pts[i,], add = T, pch = 16, col = Color)
}
#dev.off()
#system("convert -delay 80 *.png example_1.gif")
```


```{r}
rbPal <- colorRampPalette(c("cadetblue1", "palevioletred1"))
Color <- rbPal(100)[as.integer(pts$TAVG)]
```

```{r}
dir.create("examples")
setwd("examples")

# example 1: simple animated countdown from 10 to "GO!".
png(file="example%02d.png", width=200, height=200)
  for (i in c(10:1, "G0!")){
    plot.new()
    text(.5, .5, i, cex = 6)
  }
dev.off()

# convert the .png files to one .gif file using ImageMagick. 
# The system() function executes the command as if it was done
# in the terminal. the -delay flag sets the time between showing
# the frames, i.e. the speed of the animation.
system("convert -delay 80 *.png example_1.gif")

# to not leave the directory with the single jpeg files
# I remove them.
file.remove(list.files(pattern=".png"))
```

